calificacion = float(input("ingrese su calificacion"))
if calificacion >= 0 and calificacion<= 20:
    print("eres una completa basura")
elif calificacion >=20 and calificacion <=50:
    print("sigues siendo de los peorcitos")
elif calificacion >=50 and calificacion<=80:
    print("almenos ya no eres una basura")
elif calificacion >=80 and calificacion <=100:
    print("eres de lo mas bestias del salon")